#!/usr/bin/env python3
"""
Emit the E2 layer sweep as a self-contained TikZ picture for the paper.

Pure TikZ, no pgfplots: the AAAI template already loads tikz, and adding a
package to a submission that compiles is a risk with no upside. Everything is
absolute coordinates computed here, so the .tex fragment has no dependencies
beyond \\usepackage{tikz}.

    python paperfig.py results/<run-id>/e2-tierA --out fig_e2sweep.tex

Then in the paper:

    \\begin{figure}[t] \\centering \\input{fig_e2sweep} \\caption{...} \\end{figure}

Four curves, and the figure only means anything with all four:

    real         the vector captured with the skill in context
    filler       captured with a neutral document instead -- the control that
                 says whether recovery is about content or about presence
    mean         the average over items, carrying no per-item content at all
    mismatched   another item's vector, the "patching anywhere helps" control

The y axis is recovery: 1.0 reproduces the document's whole behavioural effect.
Values above 1.0 are drawn, not clipped -- on Tier A they are the finding.
"""

from __future__ import annotations

import argparse
import io
import json
import pathlib
import sys

STYLE = {
    "real":       ("skillred",  "very thick",              "real (skill)"),
    "filler":     ("skillblue", "very thick, densely dashed", "filler (neutral doc)"),
    "mean":       ("black!55",  "thick, dotted",           "mean vector"),
    "mismatched": ("black!35",  "thin",                    "mismatched item"),
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("stage_dir", type=pathlib.Path,
                    help="a run's e2-* directory (holds per_layer.jsonl)")
    ap.add_argument("--out", default="fig_e2sweep.tex")
    ap.add_argument("--width", type=float, default=7.4, help="cm")
    ap.add_argument("--height", type=float, default=4.4, help="cm")
    args = ap.parse_args()

    src = args.stage_dir / "per_layer.jsonl"
    if not src.exists():
        print(f"[FAIL] 缺 {src}")
        return 1

    rows = [json.loads(l) for l in io.open(src, encoding="utf-8") if l.strip()]
    rows.sort(key=lambda r: r["layer"])
    layers = [r["layer"] for r in rows]
    curves = {}
    for key in STYLE:
        vals = [r["recovery"].get(key) for r in rows]
        if any(v is not None and v == v for v in vals):
            curves[key] = vals
    if "filler" not in curves:
        print("  (注意) 这一跑没有 filler 条件 —— 图里会缺那条对照曲线,"
              "而它正是判断内容 vs 在场的那一条。加 --filler 重跑 e2 更好。")

    finite = [v for c in curves.values() for v in c if v is not None and v == v]
    lo, hi = min(finite + [0.0]), max(finite + [1.0])
    pad = 0.08 * (hi - lo or 1.0)
    lo, hi = lo - pad, hi + pad

    W, H = args.width, args.height

    def X(layer):
        span = (layers[-1] - layers[0]) or 1
        return W * (layer - layers[0]) / span

    def Y(v):
        return H * (v - lo) / (hi - lo)

    L = []
    a = L.append
    a("% generated by whitebox/paperfig.py -- do not edit by hand")
    a("\\definecolor{skillred}{HTML}{A93B26}")
    a("\\definecolor{skillblue}{HTML}{35697B}")
    a("\\begin{tikzpicture}[x=1cm,y=1cm,font=\\scriptsize]")

    # y=1 is the line the whole figure is read against
    if lo < 1.0 < hi:
        a(f"  \\draw[black!30,densely dotted] (0,{Y(1.0):.3f}) -- "
          f"({W:.3f},{Y(1.0):.3f});")
        a(f"  \\node[anchor=west,black!45,inner sep=1pt] at "
          f"({W+0.05:.3f},{Y(1.0):.3f}) {{$1.0$}};")
    if lo < 0.0 < hi:
        a(f"  \\draw[black!20] (0,{Y(0.0):.3f}) -- ({W:.3f},{Y(0.0):.3f});")

    a(f"  \\draw[black!45] (0,{Y(lo + pad):.3f}) -- (0,{Y(hi - pad):.3f});")
    a(f"  \\draw[black!45] (0,{Y(lo + pad):.3f}) -- ({W:.3f},{Y(lo + pad):.3f});")

    for lab in (layers[0], layers[len(layers) // 2], layers[-1]):
        a(f"  \\node[anchor=north,inner sep=2pt] at ({X(lab):.3f},"
          f"{Y(lo + pad):.3f}) {{{lab}}};")
    a(f"  \\node[anchor=north,inner sep=8pt] at ({W/2:.3f},{Y(lo+pad):.3f}) "
      f"{{layer}};")
    a(f"  \\node[rotate=90,anchor=south,inner sep=9pt] at (0,{H/2:.3f}) "
      f"{{recovery}};")

    # thin curves first so the two that carry the claim sit on top
    for key in ("mismatched", "mean", "filler", "real"):
        if key not in curves:
            continue
        colour, style, _ = STYLE[key]
        pts = " ".join(f"({X(l):.3f},{Y(v):.3f})"
                       for l, v in zip(layers, curves[key])
                       if v is not None and v == v)
        a(f"  \\draw[{colour},{style}] plot coordinates {{{pts}}};")

    y = H + 0.62
    x = 0.0
    for key in ("real", "filler", "mean", "mismatched"):
        if key not in curves:
            continue
        colour, style, label = STYLE[key]
        a(f"  \\draw[{colour},{style}] ({x:.3f},{y:.3f}) -- ({x+0.45:.3f},{y:.3f});")
        a(f"  \\node[anchor=west,inner sep=2pt] at ({x+0.5:.3f},{y:.3f}) "
          f"{{{label}}};")
        x += 0.5 + 0.06 * len(label) + 0.55
        if x > W - 1.2:
            x, y = 0.0, y - 0.42
    a("\\end{tikzpicture}")

    pathlib.Path(args.out).write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"  写好: {args.out}")
    print(f"  层 {layers[0]}..{layers[-1]}，曲线: {', '.join(curves)}")
    # Read the layer off summary.json rather than taking the max: e2_patch
    # excludes the final layers, where patching the last prompt position simply
    # overwrites the state that emits the answer token and recovery is high by
    # construction. Quoting a margin from there would quote an artefact.
    sm = args.stage_dir / "summary.json"
    best_layer = None
    if sm.exists():
        best_layer = json.loads(sm.read_text(encoding="utf-8")).get("best_layer")
    if best_layer is None:
        tail = [l for l in layers[:-2]] or layers
        best_layer = max(tail, key=lambda l: dict(zip(layers, curves["real"]))[l])
        print("  (注意) 没有 summary.json,峰值层是这里重算的（已排除末两层）")
    at = lambda k: dict(zip(layers, curves[k])).get(best_layer)
    print(f"  real 在最佳层 {best_layer}: {at('real'):+.3f}")
    if "filler" in curves and at("filler") is not None:
        print(f"  同层 filler {at('filler'):+.3f}   "
              f"内容余量 {at('real') - at('filler'):+.3f}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
